version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/account
  - /modules/iam-group
  - /modules/iam-oidc-identity-provider
  - /modules/iam-policy
  - /modules/iam-predefined-policies
  - /modules/iam-role
  - /modules/iam-saml-identity-provider
  - /modules/iam-service-linked-role
  - /modules/iam-user
  - /modules/region
  schedule:
    interval: weekly
