# Modules
":floppy_disk: account":
- changed-files:
  - any-glob-to-any-file:
    - modules/account/**/*

":floppy_disk: iam-group":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-group/**/*

":floppy_disk: iam-oidc-identity-provider":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-oidc-identity-provider/**/*

":floppy_disk: iam-policy":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-policy/**/*

":floppy_disk: iam-predefined-policies":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-predefined-policies/**/*

":floppy_disk: iam-role":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-role/**/*

":floppy_disk: iam-saml-identity-provider":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-saml-identity-provider/**/*

":floppy_disk: iam-user":
- changed-files:
  - any-glob-to-any-file:
    - modules/iam-user/**/*

":floppy_disk: region":
- changed-files:
  - any-glob-to-any-file:
    - modules/region/**/*
